"""empty message

Revision ID: 16555082cf17
Revises: 57c437c7bd89
Create Date: 2019-07-01 16:04:07.409803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16555082cf17'
down_revision = '57c437c7bd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('color_red', sa.Integer(), nullable=True),
    sa.Column('color_green', sa.Integer(), nullable=True),
    sa.Column('color_blue', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light_settings')
    # ### end Alembic commands ###
