"""empty message

Revision ID: 18c01653cc13
Revises: 16555082cf17
Create Date: 2019-07-02 09:19:07.427703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c01653cc13'
down_revision = '16555082cf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('last_contact', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'last_contact')
    # ### end Alembic commands ###
