"""empty message

Revision ID: 1c2532e4e06e
Revises: af2d83dbb94d
Create Date: 2019-02-20 19:03:45.544935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2532e4e06e'
down_revision = 'af2d83dbb94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('has_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'has_changed')
    # ### end Alembic commands ###
