"""empty message

Revision ID: 3d554b9d3324
Revises: 1c2532e4e06e
Create Date: 2019-02-25 14:55:11.207166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d554b9d3324'
down_revision = '1c2532e4e06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'nickname')
    # ### end Alembic commands ###
