"""Add static message table

Revision ID: 5e0183331cf8
Revises: 455ad6d5808d
Create Date: 2019-02-18 12:05:31.223021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0183331cf8'
down_revision = '455ad6d5808d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
