"""empty message

Revision ID: c9382b4298f9
Revises: 18c01653cc13
Create Date: 2019-07-02 13:08:03.465334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9382b4298f9'
down_revision = '18c01653cc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('healthcheck_task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcheck_task')
    op.drop_table('web_account')
    # ### end Alembic commands ###
