"""empty message

Revision ID: ea49f54d739a
Revises: 459ca10847fb
Create Date: 2019-02-19 09:30:54.449632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea49f54d739a'
down_revision = '459ca10847fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_insight_metric', sa.Column('aggregation', sa.String(), nullable=True))
    op.add_column('application_insight_metric', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('application_insight_metric', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('application_insight_metric', sa.Column('timespan', sa.String(), nullable=True))
    op.add_column('task', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'last_update')
    op.drop_column('application_insight_metric', 'timespan')
    op.drop_column('application_insight_metric', 'start')
    op.drop_column('application_insight_metric', 'end')
    op.drop_column('application_insight_metric', 'aggregation')
    # ### end Alembic commands ###
