"""empty message

Revision ID: ffb562af436d
Revises: 5e0183331cf8
Create Date: 2019-02-18 14:19:16.683890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb562af436d'
down_revision = '5e0183331cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_time_message',
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('dateformat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_column('task', 'sort_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('sort_order', sa.INTEGER(), nullable=True))
    op.drop_table('date_time_message')
    # ### end Alembic commands ###
